<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title><?php echo config::get('platform_name'); ?> - want to help?</title>

<meta lang="en" name="description" content="<?php echo config::get('platform_name'); ?> is a Platform, were committed people so called do-gooder can anonymously (use the tor browser bundle!) track their (moneyless) efforts and commitment to society - to make it transparent to society and hopefully valued." />
<meta lang="de" name="description" content="<?php echo config::get('platform_name'); ?> ist eine Platform, welche es dem engagierten Gutmenschen / Ehrenamtlichen erlaubt ihre eigene (Geldlosen) Leistungen an der Gesellschaft zu erfassen und auszuwerten und das ganze auch anonym. (Tor Bundle Browser verwenden!)" />

<meta lang="en" name="keywords" content="Book-keeping, do-gooder, committed, commitment, capture, time recording" />
<meta lang="de" name="keywords" content="Buchhaltung, Gutmensch, engagiert, engagement, festhalten, erfassen, zeitcapture" />
<meta lang="es" name="keywords" content="Libro de mantenimiento, bienhechora, comprometido, el compromiso, la captura, el tiempo de grabación" />

<!-- apple-iphone specific stuff -->
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="white">

<!-- favicons generated by faviconit.com-->
<link rel="shortcut icon" href="images/icons/favicon.ico">
<link rel="icon" sizes="16x16 32x32 64x64" href="images/icons/favicon.ico">
<link rel="icon" type="image/png" sizes="196x196" href="images/icons/favicon-192.png">
<link rel="icon" type="image/png" sizes="160x160" href="images/icons/favicon-160.png">
<link rel="icon" type="image/png" sizes="96x96" href="images/icons/favicon-96.png">
<link rel="icon" type="image/png" sizes="64x64" href="images/icons/favicon-64.png">
<link rel="icon" type="image/png" sizes="32x32" href="images/icons/favicon-32.png">
<link rel="icon" type="image/png" sizes="16x16" href="images/icons/favicon-16.png">
<link rel="apple-touch-icon" href="images/icons/favicon-57.png">
<link rel="apple-touch-icon" sizes="114x114" href="images/icons/favicon-114.png">
<link rel="apple-touch-icon" sizes="72x72" href="images/icons/favicon-72.png">
<link rel="apple-touch-icon" sizes="144x144" href="images/icons/favicon-144.png">
<link rel="apple-touch-icon" sizes="60x60" href="images/icons/favicon-60.png">
<link rel="apple-touch-icon" sizes="120x120" href="images/icons/favicon-120.png">
<link rel="apple-touch-icon" sizes="76x76" href="images/icons/favicon-76.png">
<link rel="apple-touch-icon" sizes="152x152" href="images/icons/favicon-152.png">
<link rel="apple-touch-icon" sizes="180x180" href="images/icons/favicon-180.png">
<meta name="msapplication-TileColor" content="#FFFFFF">
<meta name="msapplication-TileImage" content="images/icons/favicon-144.png">
<meta name="msapplication-config" content="images/icons/browserconfig.xml">

<!-- external styles -->
<link href="css/style.css" type="text/css" rel="stylesheet" />
<link href="css/shariff.min.css" type="text/css" rel="stylesheet" />